name: "Build and deploy to GitHub Pages"

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: "Build and deploy"
    runs-on: "ubuntu-latest"

    env:
      NODE_ENV: "production"
      NODE_VERSION: "20"

    permissions:
      contents: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Use Node.js v${{ env.NODE_VERSION }}"
        uses: "actions/setup-node@v4"
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Build"
        run: "npm run build"

      - name: "Deploy"
        uses: "JamesIves/github-pages-deploy-action@v4"
        with:
          branch: "github-pages"
          folder: "dist"
